import Card from "@components/Card"
import MainLayout from "@components/Layout/Main"
import Head from "next/head"
import Image from "next/image"

export default function Page() {
  return (
    <div className="flex flex-col">
      <Head>
        <title>CZodiac - Pools</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Card className="flex flex-col justify-center text-center p-7">
        <h1 className="font-bold text-title">CZ Pools</h1>
        <h2 className="font-semibold text-header">Stake CZF to earn partnered tokens</h2>
      </Card>

      <Card className="my-6">
        <h1 className="font-bold text-title">CZ Pools</h1>
        <h2 className="font-semibold text-header">Stake CZF to earn partnered tokens</h2>
      </Card>
    </div>
  )
}

Page.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>
}
