import Card from "@components/Card"
import MainLayout from "@components/Layout/Main"
import Head from "next/head"
import Image from "next/image"

export default function Page() {
  return (
    <div>
      <Head>
        <title>CZodiac - Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div className="h-[100vh] flex flex-col justify-center align-middle text-left max-w-md mx-auto ">
          <Card className="p-6">
            <h1 className="text-[72px] bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-500 font-extrabold text-display">
              CZodiac
            </h1>
            <h2 className="text-header">Safest High APR and stable coin borrowing AMM on BSC</h2>
          </Card>
        </div>
      </main>
    </div>
  )
}

Page.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>
}
