import Card from "@components/common/Card"
import BannerCard from "@components/common/Card/BannerCard"
import MainLayout from "@components/common/Layout/Main"
import Head from "next/head"

export default function Page() {
  return (
    <div className="flex flex-col space-y-6">
      <Head>
        <title>CZodiac - Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <BannerCard
        name="home"
        className="z-50 flex flex-col justify-center h-full text-left px-[45px] py-[65px] text-white-neutral-0"
      >
        <h1 className="z-50 font-bold text-title">CZodiac</h1>
        <h2 className="z-50 font-semibold text-header">Safest High APR and stable coin borrowing AMM on BSC</h2>
      </BannerCard>
    </div>
  )
}

Page.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>
}
